# Generated by Django 5.2.3 on 2025-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_engineerscreening'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerscreening',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
