# Generated by Django 5.2.3 on 2025-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_engineerscreening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='Specialization',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='adress',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='profesional_summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
