# Generated by Django 5.2.3 on 2025-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_engineerprofile_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='adress',
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='Longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
