# Generated by Django 5.2.3 on 2025-06-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_engineerprofile_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerprofile',
            old_name='skills',
            new_name='Bio',
        ),
    ]
