# Generated by Django 5.2.3 on 2025-06-23 12:56

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_skills_engineerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=myapp.models.profile_pic_upload_path),
        ),
    ]
