# Generated by Django 5.0 on 2025-06-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_engineerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='codeshare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharecode', models.TextField(blank=True, max_length=200000, null=True)),
            ],
        ),
    ]
