# Generated by Django 5.0 on 2025-06-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_job_completed_job_latitude_job_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.CharField(default='Untitled Job', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
