# Generated by Django 5.0 on 2025-06-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_job_title_job_job_title_job_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Untitled Job', max_length=255),
        ),
    ]
