# Generated by Django 5.0 on 2025-06-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
    ]
