# Generated by Django 5.2.3 on 2025-07-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='Longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
